### ISSUE TITLE
Hot link images

### ISSUE THREAD

**Issue by denisnazarov** [outline/rich-markdown-editor#147]
I'd like to be able to use the `![]()` syntax to hot-link an image. Right now the URL ends up being automatically linked, creating invalid Markdown.

Any way to manually parse this and work around it?

Thanks.

**Comment by tommoor** [comment]
Hey, you'd need to add support for typing out the markdown shortcut in the same way that * for bold works. It's quite complicated to do in the current setup which is why it hasn't been attempted as of yet…

At a high level, when the closing ")" is typed you'd check over the preceding sentance to see if it matches the image url pattern and then replace it with an image node. There is a lot of similar logic in the MarkdownShortcuts file.

**Comment by tommoor** [comment]
Fixed in #134
