### ISSUE TITLE
Heading name will be "h-" with non-english characters

### ISSUE THREAD

**Issue by iMuFeng** [outline/rich-markdown-editor#174]
This is caused by `slugify` https://github.com/simov/slugify/issues/59

**Comment by tommoor** [comment]
Could you describe the issue you're seeing?

**Comment by iMuFeng** [comment]
Heading name will be `h-` with non-english characters like below.

![Screenshot 2020-05-08 at 10 34 54](https://user-images.githubusercontent.com/1407009/81367440-d615fb80-911f-11ea-8387-50f014319486.png)

**Comment by iMuFeng** [comment]
How about a regular for characters to be deleted? 
```ts
function safeSlugify(text: string) {
  return `h-${escape(slugify(text, {
    remove: /[!"#$%&'()*+,\/:;<=>?@\[\]\\^_`{|}~]/g,
    lower: true 
  }).replace(".", "-"))}`;
}
```

**Comment by tommoor** [comment]
I think I need to look into the slugify module and see exactly what it's providing, I think this could work but at this point it seems like you might as well just use a regex replace.

**Comment by tommoor** [comment]
Ah, seems like we could add `strict: false` – https://github.com/simov/slugify/blob/master/slugify.js#L48

**Comment by tommoor** [comment]
Looking into this further, you're right – the regex in the library uses a whitelist that includes `\w`, very western centric! In my testing a light variation on the regex you have above works well, and because we're further escaping the slug that adds an extra level of safety if an unsafe character slips through
