### ISSUE TITLE
Add link insert menu

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#179]
A common usecase for Outline is to want to search for another document and insert a link including the title of the document.

Today we have the ability to highlight some text, then click on "link" and search for a document but this flow is clunky and requires writing the name of the link yourself and clicking several times.

We'd like to introduce a flow that is entirely keyboard driven like the block insert menu (perhaps an extension of it?) and that adds the link including the correct title automatically.

### To Do
Core functionality
- [x] allow cmd+k to be used without highlighting any existing text
- [x] allow document creation from the link menu as an option in the type-ahead
- [x] add some dummy search data to make development easier

Secondary
- [ ] render internal links with document icon or document emoji
- [ ] add "add link to page or url — cmd+k" item to `/` menu
- [ ] allow `/` to be used anywhere, not just a new line

Support

cc @thenanyu

**Comment by thenanyu** [comment]
Some functional ideas for the workflow
1. **type-ahead for existing documents**; the simplest case is to reference a document that the user already knows exists. Similar to @mentioning workflows on github, twitter, etc
2. **JIT blank document creation**; sometimes the user may want to reference documents they intend to produce or otherwise don't yet exist. Similar to wiki media or more recently Roam Research. By typing a command and some text, the user can create a blank document with the text as the title. Or the user can highlight some text and convert that to a blank document reference. This is notably different from Notion, which converts blocks of text to documents but uses the target text as the _content_ not the title

**Comment by tommoor** [comment]
This is great, 2. feels like a natural extension of 1. You type ahead, and if a matching document can't be found then there is an option to "create doc and insert link", or perhaps there is always an option to create a new doc – but at that point it's the only option.

**Comment by thenanyu** [comment]
- [ ] allow `/` to be used anywhere, not just a new line
- [ ] add "add link to page or url — cmd+k" item to `/` menu
- [ ] render internal links with document icon or document emoji
- [ ] allow document creation from the link menu as an option in the type-ahead
- [ ] add some dummy search data to make development easier
