### ISSUE TITLE
Improve selection state of embeds

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#242]
- [x] It's difficult to tell when embeds are selected
- [x] It's impossible to get the caret between two embeds that have no empty paragraph between

**Comment by Hless** [comment]
Hiya, I've forked this project and have worked on some specific features for Images and Embed that solve this problem specifically. Our fork has removed some features that were not needed in the project (since was no way to customize the toolbar/available plugins).

But if you're interested you might want to take a look at this commit:
https://github.com/outline/rich-markdown-editor/commit/90b22f4029b87025ee0815572126f97778291e2e
