### ISSUE TITLE
Hyperlinks are posted between < >'s

### ISSUE THREAD

**Issue by icellan** [outline/rich-markdown-editor#608]
**To Reproduce**
Paste a link into the editor.
Link is pasted as "\<https://......\>", with < > brackets

**Expected behavior**
Link is either pasted as clear text or as a Markdown link \[title\]\(URL\)

**Version**
11.19.4

**Comment by tommoor** [comment]
Hey – this is expected behavior and differentiates links that were made by the user and those that were auto-linked. Not using clear text allows having url-like objects in the text that are not linked in the editor.

`<>` is valid link syntax in the majority of markdown parsers (there is no official spec)

**Comment by icellan** [comment]
@tommoor Thanks for the feedback. Is there some way to overwrite the way this is done? ATM I am replacing this with regex.

**Comment by tommoor** [comment]
This is the code you'd need to edit:

https://github.com/outline/rich-markdown-editor/blob/main/src/marks/Link.ts#L146-L160
